apiVersion: v1
kind: Service
metadata:
  name: connect-4-backend-service
  labels:
    app: connect-4-backend-service
spec:
  type: ClusterIP
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: connect-4-backend-deployment